#:kivy 1.11.1
    
<DateTime>:
    orientation: 'horizontal'
    Label:
        #id: my_time
        text: root.now_time.text 
        font_size: 20
        color: (0.365, 0.678, 0.925, 1)
    Label:
        #id: my_date
        text: root.now_date.text
        font_size: 20   
        color: (0.365, 0.678, 0.925, 1)
<LoginPage>:
    FloatLayout:
        DateTime:
            size_hint: 1, 0.2
            pos_hint: {"top": 1}
        Label:
            size_hint: 1, 0.2
            pos_hint: {"top": 0.85}
            text: 'VGU Server IoT Kit'
            bold: True
            font_size: 32 
            color: (0.365, 0.678, 0.925, 1)
        FloatLayout:
            Label:
                size_hint: 0.5, 0.1
                id: info
                text: ''
                markup: True
                bold: True
            TextInput:
                id: username
                hint_text: 'Username'
                text: 'abc'
                halign: 'center'
                size_hint: 0.5, 0.1
                pos_hint: {"center_x":0.5,"top":0.6}
                font_size: 18
                focus: True
                multiline: False
                write_tab: False
                on_text_validate: password.focus = True
            TextInput:
                id: password
                hint_text: 'Password'
                text: '123'
                halign: 'center'
                size_hint: 0.5, 0.1
                pos_hint: {"center_x":0.5,"top":0.45}
                multiline: False
                font_size: 18
                password: True
                write_tab: False
                on_text_validate: root.check_login()
            Button:
                id: login_button
                text: 'Log In'
                size_hint: 0.5, 0.15
                pos_hint: {"center_x":0.5,"top":0.2}
                font_size: 18 
                on_release: root.check_login()
            Label:
<TaskbarButton@Button>:
    font_size: 18
    background_color: (1, .404, 0, 1)
    background_normal: ''
    background_donw: ''
<BackgroundColor@Widget>
    background_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos
<UnderInfo@Label+BackgroundColor>:
    size_hint: 1, 0.07
    pos_hint: {"center_x": 0.5, "y":0}
    text: "Nguyen Minh Thien - Dang Van Phuoc - Le Huu Tuan Huy - Tran Gia Phuc - EEIT 2017"
    font_size: 17
    #color: (0.365, 0.678, 0.925, 1)
    #bold: True  
    background_color: (0.122, 0.459, 0.996, 1)
    #background_normal: ''
<Taskbar>:
    size_hint_y: None
    pos_hint: {"y":0.07}
    orientation: 'horizontal'
    TaskbarButton:
        text: 'Home'
        on_release: root.btn_home()
         
    TaskbarButton:
        text: 'Report'
        on_release: root.btn_report()
    TaskbarButton:
        text: 'AC Control'
        on_release: root.btn_ac()
    TaskbarButton:
        text: 'Email'
        on_release: root.btn_email()
    TaskbarButton:
        text: 'Settings'
        on_release: root.btn_settings()
    TaskbarButton:
        text: 'Log'
        on_release: root.btn_log()
<Status>:
    FloatLayout:
        DateTime:
            size_hint: 1, 0.2
            pos_hint: {"top": 1}
        Taskbar:
            size: root.width, root.height/5
        UnderInfo:

<ACControl>:
    FloatLayout:
        Taskbar:
            size: root.width, root.height/5
        UnderInfo:
<Email>:
    FloatLayout:
        Taskbar:
            size: root.width, root.height/5
        UnderInfo:
<Setting>:
    FloatLayout:
        Taskbar:
            size: root.width, root.height/5
        UnderInfo:
<Report>:
    FloatLayout:
        Taskbar:
            size: root.width, root.height/5
        UnderInfo:
<Log>:
    FloatLayout:
        Taskbar:
            size: root.width, root.height/5
        UnderInfo:

            